apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todolist
  name: todolist
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - image: xxucici/newtask
        name: newtask
        ports:
          - containerPort: 6080
        env:
            - name: LISTEN_BROKER
              value: nats
            - name: LISTEN_OPTIONS_SERVERS
              value: nats://listen-broker.default.svc.cluster.local:6080
            - name: LISTEN_CHANNELS
              value: tasks,notifications
---        
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  type: LoadBalancer
  selector:
    app: todolist
  ports:
    - port: 6080
      targetPort: 6080